<a href="https://colab.research.google.com/github/antidude900/pytorch_learning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.4.1+cu121


In [ ]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7,4])
vector

tensor([7, 7, 4])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape
vector

tensor([7, 7, 4])

In [ ]:
Matrix = torch.tensor([[8,9,4,6],
                       [2,3,9,8],
                       [4,5,1,3]])
Matrix

tensor([[8, 9, 4, 6],
        [2, 3, 9, 8],
        [4, 5, 1, 3]])

In [ ]:
Matrix.ndim

2

In [ ]:
Matrix.shape

torch.Size([3, 4])

In [ ]:
Matrix[0][2]

tensor(4)

In [ ]:
Tensor = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9],
                       [10,11,12]],
                       [[1,2,3],
                       [4,5,6],
                       [7,8,9],
                       [10,11,12]]])
Tensor

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],

        [[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])

In [ ]:
Tensor.ndim

3

In [ ]:
Tensor.shape

torch.Size([2, 4, 3])

In [ ]:
t = torch.rand(2,3 ,dtype=float)
print(t.device)

cpu


In [ ]:
random_tensor1 = torch.rand(5,6,7,3,4)
random_tensor2 = torch.rand((5,6,7,3,4))
random_tensor3 = torch.rand(size=(5,6,7,3,4))
print(f'1:{random_tensor1.shape,random_tensor1.shape}')
print(f'2:{random_tensor2.shape,random_tensor2.shape}')
print(f'3:{random_tensor3.shape,random_tensor3.shape}')

1:(torch.Size([5, 6, 7, 3, 4]), torch.Size([5, 6, 7, 3, 4]))
2:(torch.Size([5, 6, 7, 3, 4]), torch.Size([5, 6, 7, 3, 4]))
3:(torch.Size([5, 6, 7, 3, 4]), torch.Size([5, 6, 7, 3, 4]))


In [ ]:
torch.add(random_tensor1,random_tensor2)

tensor([[[[[0.3079, 1.3918, 1.2405, 1.3456],
           [1.3321, 0.6866, 1.2907, 1.2398],
           [1.5809, 0.8020, 0.7530, 1.2589]],

          [[0.8922, 1.4569, 1.2470, 1.0912],
           [1.4512, 1.3641, 0.8903, 1.5023],
           [1.6779, 0.5125, 1.0567, 0.6594]],

          [[1.4589, 0.9346, 0.1251, 0.4780],
           [0.6182, 1.0842, 1.0534, 0.8132],
           [1.2251, 0.5221, 0.8696, 0.6582]],

          ...,

          [[1.1589, 1.2915, 0.2362, 1.1605],
           [1.4150, 1.1204, 0.6884, 0.9427],
           [1.4801, 0.9731, 1.6030, 0.3342]],

          [[1.3063, 0.2740, 1.0149, 0.9305],
           [1.2161, 1.3663, 1.0881, 0.6445],
           [0.9860, 1.1245, 1.1537, 0.1125]],

          [[0.8760, 1.0566, 0.9268, 0.5796],
           [0.7493, 0.8412, 0.3793, 1.0404],
           [1.3459, 1.1298, 0.9722, 0.9678]]],


         [[[1.1145, 0.3409, 1.2545, 0.7332],
           [1.1443, 1.0344, 0.5363, 1.5064],
           [0.8226, 1.1628, 0.8061, 0.6174]],

          [[0.9706, 1.2

In [ ]:
x = torch.arange(1,10)
x,x.size()

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
y=x.reshape(1,9)
y,y.size()

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
z=x.reshape(9,1)
z,z.size()

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [ ]:
x = torch.arange(1,10)
x,x.size()
k = x.view(9,1)
k=0
k,x

(0, tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
x = torch.arange(1,19).reshape(2,3,3)
x

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [ ]:
x[:,0,:]

tensor([1, 2, 3])



1.   For finding the whole dimension of a tensor(whether the tensor is 2D or 3D or ...?), see how many square brackets we have to go through to get to the items.

2.   For finding the size of a tensor on nth dimension(meaning if 2D dimension tensor, we have 1st dimenstion and 2nd dimension), see how many square it covers in that dimension.

3. For finding the index of a certain element or part of a tensor, keep in mind that the first element's/part's position is denoted as 0 meaning tensors are 0-indexed.

4. While indexing, we can use ":" meaning all the data inside that dimension are selected.

5. Unsqueezing means unpacking each element in seperate ranks(a rank for each element)[Rank means new row i.e each square bracket at the same dimension represents a rank]. It gives the feeling of unsqueezing as instead of squeezing all the elements in a single rank, we are spreading them in seperate ranks thus unsqueezing. Hence doing this, it adds a dimension in the shape of the tensor which is singleton meaning each rank in that dimension contains a single element.






In [ ]:
arr = torch.Tensor([1,2,3,4,5])
arr.reshape(5,1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.]])

In [ ]:
device  = "cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
tensor = torch.tensor([1,2,3])
tensor.device

device(type='cpu')

In [ ]:
tensor.to(device)

tensor([1, 2, 3], device='cuda:0')